[package]
name = "json2csv-lite"
version = "0.1.0"
authors = ["Clément Renault <renault.cle@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1.1"
serde_json = "1.0.44"
main_error = "0.1.0"
memmap = "0.7.0"
